# Decision matrix {#sec-top .unnumbered}

You can use the decision tool below to help choose which R packages may be right for your application:

1. Look first for the desired output that you want to produce
1. Then see which set of required data you have. If you do not have the required data for a specific package, use a different one
1. Finally, estimate $R(t)$ using the packages that are appropriate for your use case

<small>See below the table for the assessment framework used to decide which packages to recommend.</small>

::: {.callout-important}
## Strong recommendation
**Use multiple packages** in your analysis; an ensemble of approaches will be the best way to ensure a robust estimate of $R(t)$ for your use case. 
:::

```{=html}
<table>
    <caption>Decision matrix for choosing R(t) estimation tool</caption>
    <!---HEADING --->
    <tr style="border-top: none; background-color: lightgrey;">
      <th style="font-weight: bold; width: 30%">Desired output</th>
      <th style="font-weight: bold; width: 40%">Data required</th>
      <th style="font-weight: bold; width: 30%">Package options</th>
    </tr>
    <!---GROUP 1: NOW-CASTING --->
    <tr style="border-top: 2px solid;">
        <td rowspan="2">
          What will R(t) be <u>next week</u> <div style="height:10px;"><br></div>
          <small>i.e., forcasting or nowcasting applications</small>
        </td>
        <td>
          ☐ Daily reported case counts <div style="height:1px;"><br></div>
          ☐ Serial interval <div style="height:1px;"><br></div>
          ☐ Reporting delay distribution
        </td>
        <td>
            <a href="package_EpiNow2.html#sec-top">EpiNow2</a>, 
            Option2
        </td>
    </tr>
    <tr>
        <td> 
          ☐ Wastewater suriveillance data <div style="height:1px;"><br></div>
          ☐ 
        </td>
        <td>no plan yet</td>
    </tr>
    <!---GROUP 2: Recent Historical --->
    <tr style="border-top: 2px solid;">
        <td rowspan="2">
          What was R(t) in the <u> past week</u>
        </td>
        <td>
          ☐ Daily reported case counts <div style="height:1px;"><br></div>
          ☐ Serial interval <div style="height:1px;"><br></div>
          ☐ Reporting delay distribution
        </td>
        <td>
            <a href="package_RtEstim.html#sec-top">RtEstim</a>, 
            Option2
        </td>
    </tr>
    <tr>
        <td>Wastewater </td>
        <td>no plan yet</td>
    </tr>
    
        <!---GROUP 3: Past Historical --->
    <tr style="border-top: 2px solid;">
        <td rowspan="2">
          What was R(t) historically
        </td>
        <td>
          ☐ Daily reported case counts <div style="height:1px;"><br></div>
          ☐ Serial interval <div style="height:1px;"><br></div>
          ☐ Reporting delay distribution
        </td>
        <td>
            <a href="package_EpiEstim.html#sec-top">EpiEstim</a>, 
            Option2
        </td>
    </tr>
    <tr>
        <td>Wastewater </td>
        <td>no plan yet</td>
    </tr>
    
</table>

```

### Assessment framework {#sec-assessment}

An objective comparison of the performance of the methods in these packages would be highly complex, given the following challenges:

- Some of the most widely-used packages are not accompanied with a peer-reviewed manuscript that describes or evaluates the theory behind modeling choices. 
- Each package contains a subset of the methods below for constraining $R(t)$ in time, but with subtle variations in implementation that are often not well-documented. 
- Some packages have not been recently updated, and even those that have are not maintained on CRAN, instead leaving updates on a development version on GitHub. 
- Performance may vary widely considering additional factors like ease of implementation and computational time.
- it also may be the case that some methods of temporal smoothing work better
    in some cases versus other (very low case counts, rapid changes)

Indeed, many published validation efforts are often not "apples to apples", i.e., comparing two models that are using different amounts of information in estimating R(t). For example, comparing a model that has used only data before time before t to estimate R(t) versus a model that uses the entire historical record to estimate R(t) at time t.

Instead, we present some some subjective reflections on various aspects of utilizing each package. These were assessed by consensus among the various authors and co-authors:

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 20%">Category</th>
      <th style="font-weight: bold; width: 30%">Notes</th>
      <th style="font-weight: bold; width: 50%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>
    
    <tr>
        <td>Ease of installation</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
        <tr>
        <td>Ease of use</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
    
            <tr>
        <td>Ease of extractring output</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
            <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
                <tr>
        <td>Ability to nowcast/forcast</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases and R(t)</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>
    
                        <tr>
        <td>Clarity of documentation</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>

                        <tr>
        <td>Intrepetability of outputs</td>
        <td>Some description</td>
        <td>
          ☐ Easy: description <div style="height:1px;"><br></div>
          ☐ Moderate: description <div style="height:1px;"><br></div>
          ☐ Challenging: description
        </td>
    </tr>

</table>

```
