# Inference frameworks {#sec-introduction .unnumbered}

Finally there are different ways of acutally calculating the numbers once you have the theory lined up.

## Bayesian optimization

	Assumes a distribution --> solved analytically
•	EpiEstim
o	restricted set of GI options (gamma?) enables analytical solve for the posterior estimate of R(t) which is also a Gamma, using conjugate priors

	Doesn't assume a distribution of R(t) or I(t) --> Uses MCMC
•	EpiNow2, implemented in STAN
•	Hierarchical NUTS

## MaxLiklihood optimization

•	Frequentist
o	RtEstim

Wallinga, J., and P. Teunis. "Different Epidemic Curves for Severe Acute Respiratory Syndrome Reveal Similar Impacts of Control Measures." American Journal of Epidemiology 160,no. 6 (2004): 509.
•	^ this has the likelihood calculation in it

One of the most widely used methods for estimating time-varying reproduction number is a maximum likelihood-based approach {White, 2008}. 
•	White LF, Pagano M. A likelihood-based method for real-time estimation of the serial interval and reproductive number of an epidemic. Stat Med 2008; 27(16): 2999–3016.
