# Estimating R(t) { .unnumbered}

To aid with interpretation of package outputs, we summarize the currently used inputs, data, methods and assumptions in $R(t)$ estimation across the following categories:

&emsp;[⎘](methods_introduction.qmd): How the relationship between $R(t)$ and infections is defined <br>
&emsp;[⎘](methods_distributions.qmd): How $R(t)$ is constrained using distributions for key variables<br>
&emsp;[⎘](methods_time.qmd): How $R(t)$ is constrained over time<br>
&emsp;[⎘](methods_additionaldata.qmd): Additional data and distributions that are used to constrain $R(t)$<br>
&emsp;[⎘](methods_inference.qmd): Inference frameworks that are used to estimate $R(t)$<br>

We also present:

&emsp;[⎘](simulation_tool.qmd#): An Rshiny application for simulation of case data and $R(t)$<br>
&emsp;[⎘](methods_research.qmd): A list of open research questions<br>

We limit the methods discussed here to those for estimating historical to present-day $R(t)$ values using **daily case count data**, where a case can be flexibly defined as an individual with a reported positive test (either through healthcare-seeking behavior, routine surveillance, or a hospital admission). 

### Other methods not discussed here include:

- inference of $R(t)$ exclusively from alternative data sources (e.g., genetic data [@Walker2013Whole], behavioral data [@Bokanyi2023Real], or viral loads in waste-water [@Huisman2022Wastewater]), 
- calculations from compartmental, agent-based models, or network [@Driessche2002Reproduction, @Almutiry2021Continuous, @Bettencourt2008Real].

We also limit the discussion to packages in the statistical software R [@R2022R], which may exclude some packages in other software programs that combine many of the methodological considerations discussed below [@Yang2022Bayesian]. 

The methods discussed below and references to specific R packages are current as of December 1, 2024. We attempt to harmonize the mathematical choices between each package using terminology from each.

