# earlyR { .unnumbered}

| | 
|:---|:--------|
| REF| None|
| Docs| [repidemicsconsortium.org/earlyR/articles/earlyR.html](https://www.repidemicsconsortium.org/earlyR/articles/earlyR.html)|
| Github| [github.com/reconhub/earlyR](https://github.com/reconhub/earlyR) |
| Last commit| October 27, 2020|
| Installation | [CRAN](https://cran.r-project.org/web/packages/earlyR/index.html)|
: {tbl-colwidths="[20,80]"}

### Brief description
<div style="font-size:0.8em">Copied from the developer site<br><br></div>

Implements a simple, likelihood-based estimation of the reproduction number (R0) using a branching process with a Poisson likelihood. This model requires knowledge of the serial interval distribution, and dates of symptom onsets. Infectiousness is determined by weighting R0 by the probability mass function of the serial interval on the corresponding day. It is a simplified version of the model introduced by @Cori2013New.

### Methods

This package does not constrain R in time, instead this is meant to predict a single R value (R0) and then uses this to nowcast and forecast cases.

### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| Yes|
| Incorporates delay distributions| No|
| Estimates expected cases| Yes|
| Communicates uncertainty| Yes|
|<strong>Validation</strong>||
| Documentation of package methods| No|
| Documentation of package implementation| Yes|
: {tbl-colwidths="[40,60]"}

### Sample Code

[This vignette](https://cran.r-project.org/web/packages/earlyR/vignettes/earlyR.html) gives a basic example of usage

