# epigrowthfit { .unnumbered}

| | 
|:---|:--------|
| REF| |
| Peer reviewed| ❌✅|
| Docs| |
| Github|  |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description

| [epigrowthfit](package_epigrowthfit.qmd) | @Earn2020Acceleration | [🔗](https://github.com/davidearn/epigrowthfit) | Aug 12, 2024|

::: {style="font-size:0.8em"}
Copied from the developer site.<br><be>
:::

Maximum likelihood estimation of nonlinear mixed effects models of epidemic growth using Template Model Builder ('TMB'). Enables joint estimation for collections of disease incidence time series, including time series that describe multiple epidemic waves. Supports a set of widely used phenomenological models: exponential, logistic, Richards (generalized logistic), subexponential, and Gompertz. Provides methods for interrogating model objects and several auxiliary functions, including one for computing basic reproduction numbers from fitted values of the initial exponential growth rate. Preliminary versions of this software were applied in Ma et al. (2014) <doi:10.1007/s11538-013-9918-2> and in Earn et al. (2020) <doi:10.1073/pnas.2004904117>

### Methods

This package contains the following methods:

- 

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>
          no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>
          no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>
          no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>
no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>
          no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>GitHub site and R package</td>
        <td>
          Yes
        </td>
    </tr>


</table>

```



### Sample code


