# EpiEstim { .unnumbered}

| | 
|:---|:--------|
| REF|@Cori2013New, @Nash2023Estimating|
| Peer reviewed| ✅|
| Docs| [mrc-ide.github.io/EpiEstim](https://mrc-ide.github.io/EpiEstim/)|
| Github| [github.com/mrc-ide/EpiEstim](https://github.com/mrc-ide/EpiEstim) |
| Last commit| Aug 30, 2024|
| Installation | [CRAN](https://cran.r-project.org/web/packages/EpiEstim/index.html)|
: {tbl-colwidths="[20,80]"}

### Brief description
<div style="font-size:0.8em">Copied from the developer site<br><br></div>

EpiEstim is a tool to estimate the time-varying instantaneous reproduction number during epidemics. In order to estimate Rt, EpiEstim needs to be supplied with an estimate of the serial interval distribution (step A) and the incidence of confirmed cases (step B). Once you have an incidence object (based on the dates of symptom onset) and information on the serial interval distribution, we can use the renewal equation (a form of branching process model) to estimate Rt. The incidence of symptom onset at time t is approximated by a Poisson process using the renewal equation. 

Note: EpiEstim runs quickly owing


### Methods

This package contains the following methods:

- [fixed sliding windows](methods_time.qmd#sec-fixedwindow)


### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No|
| Incorporates delay distributions| No, although some right-censoring is included|
| Estimates expected cases| No|
| Communicates uncertainty| Yes|
|<strong>Validation</strong>||
| Documentation of package methods| Yes|
| Documentation of package implementation| Yes|
: {tbl-colwidths="[40,60]"}

### Sample Code

[This vignette](https://mrc-ide.github.io/EpiEstim/articles/full_EpiEstim_vignette.html) gives a basic example of usage of EpiEstim.

The end of this vignette suggests using the `projections` package to estimate future cases, and we cannot recommend this package. The estimation of future values of R(t) in this package comes from resampling different past values of R(t) rather than trends dervied from recent infections. 
