# bayEstim {.unnumbered}

| | 
|:---|:--------|
| REF| [Lytras et al. - medRxiv](https://www.medrxiv.org/content/10.1101/2020.09.19.20198028v1)|
| Docs| None|
| Github| [github.com/thlytras/bayEStim](https://github.com/thlytras/bayEStim) |
| Last commit| Aug 3, 2020|
| Installation | None|
: {tbl-colwidths="[20,80]"}

### Brief description

This package extends the method of Cori et al (2013), adding Bayesian imputation of missing symptom onset dates, imputation of infection times using an external estimate of the incubation period, and an adjustment for reporting delay. This was never submitted to CRAN, no further action taken.


### Methods

This package contains the following methods:

- [fixed sliding windows](methods_time.qmd#sec-fixedwindow)


### Assessment

| | 
|:---|:--------|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No|
| Incorporates delay distributions| No, although some right-censoring is included|
| Estimates expected cases| No|
| Communicates uncertainty| No|
|<strong>Validation</strong>| No|
| Documentation of package methods| No|
| Documentation of package implementation| No|
: {tbl-colwidths="[40,60]"}



