# EpiNow2 {.unnumbered}

### Description
<div style="font-size:0.8em">Copied from the developer site<br><br></div>

[EpiNow2](package_EpiNow2.qmd) estimates the time-varying reproduction number on cases by date of infection (using a similar approach to that implemented in [EpiEstim](package_EpiEstim.qmd)). True infections, treated as latent and unobserved, are estimated and then mapped to observed data (for example cases by date of report) via one or more delay distributions (in the examples in the package documentation these are an incubation period and a reporting delay) and a reporting model that can include weekly periodicity.

Uncertainty is propagated from all inputs into the final parameter estimates, helping to mitigate spurious findings. This is handled internally. The time-varying reproduction estimates and the uncertain generation time also give time-varying estimates of the rate of growth.

Forecasting is also supported for the time-varying reproduction number, infections, and reported cases using the same generative process approach as used for estimation.

<small style="font-weight: bold;margin-bottom: 0;">Important links:</small>

| | | | |
|:---|:--|:----|:----|
|<small>REF: </small> [Wellcome report](https://wellcomeopenresearch.org/articles/5-112) <br><small>(Peer reviewed: ❌)</small> | [Docs](https://epiforecasts.io/EpiNow2/) | [Github](https://github.com/epiforecasts/EpiNow2) <small><br>(Updated: Mar 2025)</small>| [CRAN](https://cran.r-project.org/web/packages/EpiNow2/index.html) <small><br>(Updated: Feb 2025)</small>|  
: {tbl-colwidths="[30,10,30,30]"}


### Methods

This package contains the following methods:

- [Gaussian Process](methods_time.qmd#sec-gaussianprocess)


### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
☐ Yes/no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>


</table>

```



### Starter code

- copy in from SummRT
- all things should use the same datasets
- could make these shiny apps if we wanted
