# R0 { .unnumbered}

| | 
|:---|:--------|
| REF| |
| Docs| |
| Github|  |
| Last commit| |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description

A package that implements existing methods to estimate $R_0$ and $R_t$. The advantage of this package is that it standardizes data formats and the parameterization of the generation interval.

This package was developed in 2012 before many of the current methods were developed and most of the methods that are described in the package are not commonly used.

| [R0](package_R0.qmd) | @obadia2012r0 | [🔗](https://github.com/tobadia/R0) | Sep 20, 2023|

### Methods

This package contains the following methods:

- Function to define the generation interval. Options include empiric (i.e. multinomial), lognormal, gamma, and weibull distributions.
- Estimation of $R_0$ as a function of the attack rate (user must provide this).
- Method to estimate $R_0$ from the exponential growth rate described by [`Wallinga and Lipsitch`](https://pubmed.ncbi.nlm.nih.gov/17476782/).
- Maximum likelihood based estimate of $R_0$ and serial interval introduced by [`White and Pagano`](https://pubmed.ncbi.nlm.nih.gov/18058829/).
- Sequential Bayesian method to estimate time-varying reproductive number introduced by [`Bettencourt and Ribiero`](https://pubmed.ncbi.nlm.nih.gov/18478118/).
- Retrospective estimation of the time-varying reproductive number introduced by [`Wallinga and Teunis`](https://pubmed.ncbi.nlm.nih.gov/15353409/).

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Not described. But methods used are not computationally complex.</td>
        <td>
          N/A
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Not available in the provided methods.</td>
        <td>
          No
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Not available in the provided methods</td>
        <td>
          No
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Not available in the provided methods</td>
        <td>
          No
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some methods allow for this.</td>
        <td>
Yes
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Documentation of package methods</td>
        <td>Peer reviewed paper published describing the package.</td>
        <td>
          Yes
        </td>
    </tr>
    
                        <tr>
        <td>Documentation of package implementation</td>
        <td>Package is on Installation.</td>
        <td>
          Yes
        </td>
    </tr>


</table>

```



### Sample code
