# WhiteLabRt { .unnumbered}

| | 
|:---|:--------|
| REF| |
| Peer reviewed| ❌✅|
| Docs| |
| Github|  |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description

This package implements methods described in [`Li & White`](https://journals.plos.org/ploscompbiol/article?id=10.1371/journal.pcbi.1009210) for backcalculation and nowcasting and [`Zhou et al`](https://pubmed.ncbi.nlm.nih.gov/36048890/) for small area estimation using mobility data. The package uses stan to improve computational efficiency and stability. All methods are implemented in a Bayesian framework. Currently the package does not allow the user to incorporate both mobility data and do nowcasting and account for reporting delays.

| [WhiteLabRt](package_WhiteLabRt.qmd) | @Li2021Bayesian | [🔗](https://github.com/cmilando/WhiteLabRt) | Aug 16, 2024|

### Methods

This package contains the following methods:

- Bayesian methods to integrate multiple data sources.
- Mobility data in a hierarchical model to obtain spatially granular estimates.
- Adjustment for reporting delay and nowcasting estimates.

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 20%">Category</th>
      <th style="font-weight: bold; width: 50%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Included in the package.</td>
        <td>
          Yes
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Bayesian implementation of this.</td>
        <td>
          Yes
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Included in all methods.</td>
        <td>
          Yes
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Credible intervals included for all estimates.</td>
        <td>
Yes
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Peer reviewed publications for both methods.</td>
        <td>
          Yes
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Vignette and documentation provided.</td>
        <td>
          Yes
        </td>
    </tr>


</table>

```



### Sample code
