# EpiFusion {#sec-top .unnumbered}


### Brief description

| [EpiFusion](package_EpiFusion.qmd#sec-top) | @Judge2024EpiFusion | [🔗](https://github.com/ciarajudge/EpiFusion) | Nov 30, 2024|

::: {style="font-size:0.8em"}
Brief summary of EpiFusion method from the paper<br><br>
:::

EpiFusion is a Bayesian framework designed to estimate the effective reproduction number by jointly analyzing epidemiological (case incidence) and phylodynamic (genomic) data using particle filtering within a particle Markov Chain Monte Carlo (pMCMC) framework. It addresses the limitations of using only epidemiological or genomic data, particularly in under-sampled outbreaks. EpiFusion combines a stochastic infection dynamics model with dual observation models: one for case incidence data and another for phylodynamic tree data. The approach involves sequential particle filtering to simulate infection trajectories, with particles weighted and resampled based on their fit to both data sources. Parameter inference is achieved through Metropolis-Hastings MCMC. EpiFusion has been validated through simulations, benchmarking against existing tools, and application to real-world outbreaks, including the 2014 Ebola outbreak in Sierra Leone.


### Methods

This package contains the following methods:

- 

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
☐ Yes/no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>


</table>

```



### Sample code
