# EpiLPS {.unnumbered}

| | 
|:---|:--------|
| REF| |
| Peer reviewed| ❌✅|
| Docs| |
| Github|  |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description

| [EpiLPS](package_EpiLPS.qmd) | @Gressani2022EpiLPS | [🔗](https://github.com/oswaldogressani/EpiLPS) | Oct 24, 2024|

::: {style="font-size:0.8em"}
Brief summary of the method from the paper<br><br>
:::
EpiLPS is a Bayesian tool for estimating the time-varying reproduction number using a robust, efficient approach. It models case counts with a Negative Binomial distribution to handle overdispersion and employs Bayesian P-splines for smoothing epidemic curves. The methodology leverages Laplace approximations to estimate the posterior distribution of the spline coefficients rapidly. Two inference methods are provided: a fast maximum a posteriori approach for quick estimates and an MCMC scheme using Langevin dynamics for thorough posterior sampling. EpiLPS delivers accurate estimates without arbitrary smoothing assumptions and has been applied to SARS-CoV-1, H1N1, and COVID-19 datasets.

### Methods

This package contains the following methods:

- 

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
☐ Yes/no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>


</table>

```



### Starter code


