# APEestim { .unnumbered}

| | 
|:---|:--------|
| REF| @Parag2020Using|
| Peer reviewed| ✅|
| Docs| None|
| Github|  [Github](https://github.com/kpzoo/model-selection-for-epidemic-renewal-models)|
| Last commit|Feb 12, 2021|
| Installation | None, this is code to augment [EpiEstim](package_EpiEstim.qmd)|
: {tbl-colwidths="[20,80]"}

### Description
<div style="font-size:0.8em">Copied from the developer site<br><br></div>

[APEestim](package_APEestim.qmd) estimates the time-varying reproduction number on cases by date of infection (using a similar approach to that implemented in [EpiEstim](package_EpiEstim.qmd)).

The quality of this estimate is highly dependent on the size of a smoothing window (k) that is employed. This code presents a method for optimally selecting k in a manner that balances reliable R(t) estimation with short-term forecasts of incidence. This method is based on the accumulated prediction error (APE) idea from information theory.

### Methods

This package aims to improve upon the limitation of [fixed sliding windows](methods_time.qmd#sec-fixedwindow), specifically by optimizing the choice of the window size in an [APE Framework](methods_time.qmd#sec-ape).

### Assessment

| | 
|:---|:--------|
|<strong>Usage</strong>||
|Runtime| similar to [EpiEstim](package_EpiEstim.qmd)|
|<strong>Features</strong>||
| Ability to nowcast/forecast| No|
| Incorporates delay distributions| No|
| Estimates expected cases| No|
| Communicates uncertainty| Yes|
|<strong>Validation</strong>||
| Peer reviewed validation| Yes|
| Replicable documentation| No|
: {tbl-colwidths="[40,60]"}

### Sample Code

See [this file](https://github.com/kpzoo/model-selection-for-epidemic-renewal-models/blob/master/apeExamples.R) in the Github repo.
