# EpiInvert { .unnumbered}

| | 
|:---|:--------|
| REF| |
| Peer reviewed| ❌✅|
| Docs| |
| Github|  |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description

| [EpiInvert](package_EpiInvert.qmd) | @Alvarez2021Computing | [🔗](https://github.com/lalvarezmat/EpiInvert) | Dec 31, 2023|

::: {style="font-size:0.8em"}
Brief summary of the method from the paper <br><br>
:::
EpiInvert is an epidemiological method that estimates the time-varying reproductive number and restores incidence curves by inverting the renewal equation using variational techniques. The approach corrects biases introduced by reporting inconsistencies, including weekly and festive biases, ensuring robust epidemic trend estimation. EpiInvert estimates Rt by inverting the renewal equation using signal processing techniques, providing a reliable measure of epidemic dynamics. It corrects systematic underreporting due to weekends and holidays by detecting anomalies based on historical trends, redistributing cases across affected days to reduce artificial fluctuations, and adjusting Rt estimates to reflect true transmission patterns. It also includes a forecasting model that predicts epidemic trends using historical trends.

### Methods

This package contains the following methods:

- 

### Assessment

```{=html}
<table>
    <caption>Assessment rubric</caption>
    <!---HEADING --->
    <tr style="border-top: none;">
      <th style="font-weight: bold; width: 40%">Category</th>
      <th style="font-weight: bold; width: 40%">Notes</th>
      <th style="font-weight: bold; width: 20%">Scales</th>
    </tr>
    
        <!------ SECTION 1: USAGE -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Usage </td>
    </tr>

    <tr>
        <td>Runtime length</td>
        <td>Some description</td>
        <td>
          Time (minutes)
        </td>
    </tr>
      
      <!------ SECTION 2: FEATURES -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Features </td>
    </tr>
        <tr>
        <td>Ability to nowcast/forecast</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
                  </td>
    </tr>
                    <tr>
        <td>Incorporates delay distributions</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Estimates expected cases </td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>

                        <tr>
        <td>Communicates uncertainty</td>
        <td>Some description</td>
        <td>
☐ Yes/no
        </td>
    </tr>

      <!------ SECTION 3: Validation -------->
    <tr columnspan="3", style="background-color: lightgrey;border-top: 2px solid;margin-top: 1;margin-bottom: 1; line-height: 1;font-size: 0.8em;">
      <td> Validation </td>
    </tr>
    
                        <tr>
        <td>Peer reviewed validation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>
    
                        <tr>
        <td>Replicable documentation</td>
        <td>Some description</td>
        <td>
          ☐ Yes/no
        </td>
    </tr>


</table>

```



### Sample code
