# EpiFilter { .unnumbered}

| | 
|:---|:--------|
| REF| @Parag2021Improved|
| Peer reviewed| ✅|
| Docs| |
| Github| [https://github.com/kpzoo/EpiFilter](https://github.com/kpzoo/EpiFilter) |
| Last commit| Dec 9, 2023 |
| Installation | |
: {tbl-colwidths="[20,80]"}

### Brief description
<div style="font-size:0.8em">Copied from the developer site<br><br></div>

Maximally informed, mean square error optimised estimates of reproduction numbers (R) over time.

Uses Bayesian recursive filtering and smoothing to maximise the information extracted from the incidence data used. Takes a forward-backward approach and provides estimates that combine advantages of [EpiEstim](package_EpiEstim.qmd) and the Wallinga-Teunis method. Method is exact (and optimal given a grid over R) and deterministic (produces the same answer on the same data).

### Methods

This package contains the following methods to solve for $R(t)$ in time:

- [filtering](methods_time.qmd#sec-filtering)

### Assessment

| | 
|:---|:--------|
|<strong>Usage</strong>||
|Runtime| minutes (uses EpiEstim)|
|<strong>Features</strong>||
| Ability to nowcast/forecast| Yes, when combined with the [projections](package_projections.qmd) package|
| Incorporates delay distributions| No, although some right-censoring is included|
| Estimates expected cases| Yes, when combined with the [projections](package_projections.qmd) package|
| Communicates uncertainty| Yes|
|<strong>Validation</strong>||
| Peer reviewed validation| Yes|
| Replicable documentation| No|
: {tbl-colwidths="[40,60]"}


### Sample code

The primary sample code comes from [this R script](https://github.com/kpzoo/EpiFilter/blob/master/R%20files/vignette.R).
